<!DOCTYPE html>

<html lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<meta charset="utf-8">
	<title>Comments</title>
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="viewport" content="width=1000,maximum-scale=1.0">
	
	<!-- TODO: are all these needed? -->
	<script src="{{contextRoot}}/handlebars-1.0.0.beta.6.js"></script>
	<script src="{{contextRoot}}/jquery-1.7.2.js"></script>
	<script src="{{contextRoot}}/debug.js"></script>
	<script src="{{contextRoot}}/datamodel.js"></script>
	<script src="{{contextRoot}}/util.js"></script>
	<script src="{{contextRoot}}/login.js"></script>
	<script src="{{contextRoot}}/profile.js"></script>
	<script src="{{contextRoot}}/prettydate.js"></script>

	<link href="{{contextRoot}}/index_files/comments.css" rel="stylesheet" type="text/css">
	
	<link href="{{contextRoot}}/index_files/common-5bb01bda113dc658d72a433a6c82f468.css"
		media="screen" rel="stylesheet" type="text/css">
	<link
		href="{{contextRoot}}/index_files/signpainter-ce675fcbe36db7f34caecc22672b72bd.css"
		media="screen" rel="stylesheet" type="text/css">
	<link href="{{contextRoot}}/index_files/sean-f90257e1b76c144a9395970611d1f49c.css"
		media="screen" rel="stylesheet" type="text/css">
	<link href="{{contextRoot}}/index_files/profile-7934634ab48ba28f071f22b2b70d2bb9.css"
		media="screen" rel="stylesheet" type="text/css">

</head>

<body class="en webkit">

<div id="content_wrapper" class="clearfix">

<div id="profile_container" class="clearfix">

<div id="profile_left" class="clearfix">

<div class="panel reviews">
<div class="header">
<h3>Login</h3>
</div>

<div class="body">
	<div id="login">
</div>
</div>

</div>

</div>

<div id="profile_right" class="clearfix">

<div class="panel reviews">
<div class="header">
</div>
<div class="body">
<div class="profile_section as_host">

